[DEFAULT]
wait_times = [
    1e-5,
    2e-5,
    4e-5,
    8e-5,
    16e-5,
    32e-5,
    64e-5,
    128e-5,
    256e-5,
    512e-5,
    1024e-5,
    2048e-5,
    5096e-5,
]
n_evals = 60
n_workers = 4
n_params_list = [10]
n_terms_list = [10]

[dask]
label = "dask"
release_gil = true
method = "dask"
