# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"                # ← must be indented under tools:
  jobs:
    pre_build:
      - sphinx-apidoc -o ./docs/src/api ./src/chemfit -f --remove-old

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .